import { Box } from "@mui/material";
import Footer from "./components/Footer";
import HeaderMenu from "./components/HeaderMenu";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderMenu />
        <Box component={"main"}>{children}</Box>
        <Footer />
      </body>
    </html>
  );
}
